active:
- biological_gas_odor_treatment
- anoxic_biogas_biodesulfurization
- bioplastics_microplastics
- biogas_upgrading_biomethanation
- advanced_oxidation_processes
- bioleaching_critical_materials
- microalgae
- single_cell_protein
