biological_gas_odor_treatment:
- TITLE-ABS-KEY(biofiltration OR "biotrickling filter" OR BTF) AND TITLE-ABS-KEY("odor
  removal" OR "VOC removal" OR "volatile organic compound")
anoxic_biogas_biodesulfurization:
- TITLE-ABS-KEY("anoxic desulfurization" OR "anoxic biodesulfurization") AND TITLE-ABS-KEY(biogas)
- TITLE-ABS-KEY ( "anoxic desulfurization" OR "anoxic biodesulfurization" OR "anoxic
  biogas" OR "anoxic H2S" OR "anoxic hydrogen sulfide" OR "anoxic biotrickling filter"
  )
bioplastics_microplastics:
- TITLE-ABS-KEY ( microplastics biodegradation AND ( "anaerobic digestion" OR "wastewater"
  OR "bioagumentation" ) )
biogas_upgrading_biomethanation:
- TITLE-ABS-KEY("biogas upgrading" OR biomethanation) AND TITLE-ABS-KEY(("hydrogen"
  OR "H2") AND ("CO2" OR "carbon dioxide"))
- TITLE-ABS-KEY ( biogas bioelectrochemical upgrading )
- TITLE-ABS-KEY ( biogas hollow fiber upgrading )
microalgae:
- TITLE-ABS-KEY(microalgae AND ("wastewater treatment" OR "nutrient removal" OR "CO2
  fixation"))
single_cell_protein:
- TITLE-ABS-KEY("single cell protein" OR "microbial protein") AND TITLE-ABS-KEY("methane"
  OR "biogas" OR "methanotrophic")
advanced_oxidation_processes:
- TITLE-ABS-KEY(("photocatalysis" OR "heterogeneous photocatalysis") AND ("TiO2" OR
  "titanium dioxide" OR "ZnO"))
bioleaching_critical_materials:
- TITLE-ABS-KEY(bioleaching AND ("platinum group metals" OR "PGM" OR "palladium" OR
  "platinum" OR "rhodium"))
